name: CI → Build & Upload to S3 (GitHub-hosted)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  OUTPUT_FILE: build-output.txt

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "Runner: $RUNNER_NAME"
          uname -a
          echo "Workspace: $GITHUB_WORKSPACE"

      - name: Prepare build output
        run: |
          echo "Using bucket: ${{ vars.BUCKET_NAME }}"
          echo "Build time: $(date -u)" > "$OUTPUT_FILE"
          echo "Repository: $GITHUB_REPOSITORY" >> "$OUTPUT_FILE"
          echo "Commit: $GITHUB_SHA" >> "$OUTPUT_FILE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Upload to S3
        env:
          BUCKET: ${{ vars.BUCKET_NAME }}
          RUN_ID: ${{ github.run_id }}
        run: |
          echo "Uploading $OUTPUT_FILE to s3://$BUCKET/artifacts/$RUN_ID/$OUTPUT_FILE"
          aws s3 cp "$OUTPUT_FILE" "s3://$BUCKET/artifacts/$RUN_ID/$OUTPUT_FILE" --acl private

      - name: Show S3 URL
        env:
          BUCKET: ${{ vars.BUCKET_NAME }}
          RUN_ID: ${{ github.run_id }}
        run: echo "✅ Uploaded to:s3://$BUCKET/artifacts/$RUN_ID/$OUTPUT_FILE"
