name: CI → Build & Upload to S3 (GitHub-hosted)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  OUTPUT_FILE: build-output.txt

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "Runner: $RUNNER_NAME"
          uname -a
          echo "Workspace: $GITHUB_WORKSPACE"

      - name: Prepare build output
        run: |
          echo "Using bucket: ${{ vars.BUCKET_NAME }}"
          echo "Build time: $(date -u)" > "$OUTPUT_FILE"
          echo "Repository: $
